/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Auditoriums {
  ageLimit: string | null;
  createdAt: Generated<Timestamp>;
  features: Generated<string[]>;
  id: string;
  name: string;
  seats: number | null;
  updatedAt: Generated<Timestamp>;
  venueId: string;
}

export interface FilmListings {
  countries: Generated<string[]>;
  createdAt: Generated<Timestamp>;
  filmId: string | null;
  genres: Generated<string[]>;
  id: string;
  kind: string;
  match: string | null;
  originalTitle: string | null;
  providerId: string;
  rating: string | null;
  runtimeMinutes: number | null;
  sourceId: string;
  titleEn: string | null;
  titleFi: string | null;
  titleSv: string | null;
  updatedAt: Generated<Timestamp>;
  year: number | null;
}

export interface Films {
  backdropPath: string | null;
  countries: Generated<string[]>;
  createdAt: Generated<Timestamp>;
  fetchedAt: Timestamp;
  finnishReleaseDate: string | null;
  genres: Generated<string[]>;
  id: string;
  imdbId: string | null;
  originalLanguage: string | null;
  originalTitle: string;
  overviewEn: string | null;
  overviewFi: string | null;
  overviewSv: string | null;
  posterPath: string | null;
  rating: string | null;
  releaseDate: string | null;
  runtimeMinutes: number | null;
  titleEn: string | null;
  titleFi: string | null;
  titleSv: string | null;
  tmdbId: number;
  trailers: Generated<Json>;
  updatedAt: Generated<Timestamp>;
}

export interface Providers {
  booking: string;
  createdAt: Generated<Timestamp>;
  homepage: string;
  id: string;
  name: string;
  platform: string;
  updatedAt: Generated<Timestamp>;
}

export interface Screenings {
  ageLimit: string | null;
  ageRecommendation: number | null;
  audio: Generated<string[]>;
  auditoriumId: string | null;
  availability: string;
  businessDate: string;
  createdAt: Generated<Timestamp>;
  dimension: string;
  dubbed: boolean | null;
  endsAt: Timestamp | null;
  fetchedAt: Timestamp;
  filmId: string | null;
  firstSeenAt: Timestamp;
  formats: Generated<string[]>;
  id: string;
  lastSeenAt: Timestamp;
  licensed: boolean | null;
  listingId: string;
  priceAmountCents: number | null;
  priceCurrency: string | null;
  priceNote: string | null;
  projection: string;
  providerId: string;
  removedAt: Timestamp | null;
  series: Generated<string[]>;
  sourceId: string;
  startsAt: Timestamp;
  subtitlesKind: string;
  subtitlesLanguages: Generated<string[]>;
  tags: Generated<string[]>;
  ticketUrl: string | null;
  unmappedLabels: Generated<string[]>;
  updatedAt: Generated<Timestamp>;
  venueId: string;
}

export interface Venues {
  address: string | null;
  city: string;
  createdAt: Generated<Timestamp>;
  id: string;
  lat: number | null;
  lon: number | null;
  name: string;
  postalCode: string | null;
  providerId: string;
  shortName: string | null;
  sourceId: string;
  updatedAt: Generated<Timestamp>;
  url: string | null;
}

export interface DB {
  auditoriums: Auditoriums;
  filmListings: FilmListings;
  films: Films;
  providers: Providers;
  screenings: Screenings;
  venues: Venues;
}
