import { execFileSync } from "node:child_process";
import { cp, mkdtemp, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { parseArgs } from "node:util";

/**
 * Refreshes vendor/leffavuoro: a reference copy of Leffavuoro's code (Shady-Dev/kino,
 * AGPL-3.0) taken from our fork. Only code and docs are copied; their data (showtimes,
 * posters) is not covered by their license and must never be committed here.
 *
 *   pnpm vendor:leffavuoro [--repo URL] [--ref BRANCH]
 *
 * Uses a shallow, sparse, blobless clone, so data/ is never even downloaded.
 */

const ROOT = new URL("..", import.meta.url).pathname;
const TARGET = join(ROOT, "vendor", "leffavuoro");

/** Upstream paths we keep. Everything else is excluded (see UPSTREAM.md). */
const INCLUDE = [
  "scripts",
  "tests",
  "docs",
  ".github/workflows",
  "README.md",
  "CLAUDE.md",
  "IDEAS.md",
  "DESIGN.md",
  "LICENSE",
];

const EXCLUDED = [
  ["data/", "showtimes, venue lists and poster art: belong to the cinemas and TMDB, not AGPL"],
  ["index.html, teatteri/, kaupunki/, en/, sv/, sitemap.xml", "pages generated by their build"],
  ["logs/, status/", "their run logs"],
  ["fonts/", "Archivo font files (OFL), not needed for reference"],
  ["git history", "about 156 MB, mostly daily data commits"],
];

const { values } = parseArgs({
  options: {
    repo: { type: "string", default: "https://github.com/pekkis/kino.git" },
    ref: { type: "string", default: "main" },
  },
});

const git = (args: string[], cwd?: string) =>
  execFileSync("git", args, { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "inherit"] }).trim();

const exists = (path: string) =>
  stat(path).then(
    () => true,
    () => false,
  );

const work = await mkdtemp(join(tmpdir(), "leffavuoro-"));
try {
  console.log(`cloning ${values.repo} (${values.ref}), code only…`);
  git([
    "clone",
    "--depth=1",
    "--filter=blob:none",
    "--no-checkout",
    "--branch",
    values.ref,
    values.repo,
    work,
  ]);
  git(["sparse-checkout", "set", "--no-cone", ...INCLUDE.map((p) => `/${p}`)], work);
  git(["checkout", values.ref], work);
  const [sha, date, subject] = git(["log", "-1", "--format=%H%n%cI%n%s"], work).split("\n");

  await rm(TARGET, { recursive: true, force: true });
  const missing: string[] = [];
  for (const path of INCLUDE) {
    const from = join(work, path);
    if (await exists(from)) await cp(from, join(TARGET, path), { recursive: true });
    else missing.push(path);
  }

  await writeFile(
    join(TARGET, "UPSTREAM.md"),
    `# Vendored: Leffavuoro (Shady-Dev/kino)

A **reference copy** of [Leffavuoro](https://github.com/Shady-Dev/kino)'s code, so we can read how it
handles each ticketing platform and keep it even if the original disappears. It is not built, run,
linted or formatted here.

| | |
| --- | --- |
| Source | ${values.repo.replace(/\.git$/, "")} (our fork of [Shady-Dev/kino](https://github.com/Shady-Dev/kino)) |
| Branch | \`${values.ref}\` |
| Commit | \`${sha}\` |
| Commit date | ${date} |
| Commit message | ${subject} |
| Vendored on | ${new Date().toISOString().slice(0, 10)} |

**Update:** sync the fork with upstream on GitHub, then run \`pnpm vendor:leffavuoro\` and commit the
diff. The diff shows what changed upstream since the last copy.

## License

The code is **AGPL-3.0-or-later**, Copyright (C) 2026 Shady-Dev (see [LICENSE](LICENSE)), compatible
with this project's own AGPL-3.0-or-later license. Code ported from here into our packages must say so
at the top of the file, e.g. \`// Ported from Shady-Dev/kino scripts/providers/etiketti.py (AGPL-3.0)\`.

## Included

${INCLUDE.map((p) => `- \`${p}\``).join("\n")}
${missing.length ? `\nNot present upstream at this commit: ${missing.map((p) => `\`${p}\``).join(", ")}\n` : ""}
## Excluded, and why

${EXCLUDED.map(([what, why]) => `- ${what}: ${why}`).join("\n")}

Their README is explicit that the license covers the code and nothing else: forking grants no right
to the data. Never copy their \`data/\` into this repository.
`,
  );
  console.log(`vendor/leffavuoro updated to ${sha.slice(0, 12)} (${date})`);
  if (missing.length) console.warn(`not present upstream: ${missing.join(", ")}`);
} finally {
  await rm(work, { recursive: true, force: true });
}
